import React from 'react'
import Form from './Form'
import FormRow from './FormRow'
import FormTextInput from './FormTextInput'
import FormTagInput from './FormTagInput'
import FormTextArea from './FormTextArea'
import FormSelect from './FormSelect'

const renderComponentId = id => <FormRow
    label="ID"
    element={<div>{id}</div>}
    description="The unique ID for this component generated by the system." />

const renderMainField = (selected, choices) => <FormRow
    label="Main field"
    element={<FormSelect value={selected} choices={choices} />}
    description="Give the field a unique name." />

export default ({component = {}, fields = [], onChange, actions, errors = {}}) => {

  return (<Form actions={actions}>

        { component._id ? renderComponentId(component._id) : null }

        <FormRow
          label="Name"
          element={<FormTextInput name="name" value={component.name} onChange={onChange} />}
          description="Give the field a unique name."
          validate={ value => value || 'This field is required!!!' }
          errors={errors.name} />

        <FormRow
          label="Label"
          element={<FormTextInput name="label" value={component.label} onChange={onChange} />}
          errors={errors.label} />

        <FormRow
          label="Description"
          element={<FormTextArea name="description" value={component.description} onChange={onChange} />}
          errors={errors.description} />

        <FormRow
          label="Types"
          element={<FormTagInput name="types" value={component.types || []} onChange={onChange} />}
          description="To which components does this component conform?"
          errors={errors.types} />

        { fields ? renderMainField(fields) : null }


      </Form>)
}
