

import React from 'react'
import ButtonLink from './ButtonLink'
import Heading from './Heading'
import Form from './Form'
import FormRow from './FormRow'
import FormTextInput from './FormTextInput'
import FormTagInput from './FormTagInput'
import FormTextArea from './FormTextArea'
import FormToggle from './FormToggle'
import { pathToFields } from '../helpers'


export default ({component, field}) => {

  return (<div>

      <ButtonLink to={pathToFields(component._id)} label="Back to list" size="small" />
      <Heading>{ field.label }</Heading>
      <Form>

        <FormRow
          label="ID"
          element={<div>{field.__id}</div>}
          description="The unique ID for this field generated by the system." />

        <FormRow
          label="Name"
          element={<FormTextInput value={field.name} />}
          description="Give the field a unique name." />

        <FormRow
          label="Label"
          element={<FormTextInput value={field.label} />} />

        <FormRow
          label="Description"
          element={<FormTextArea value={field.description} />} />

        <FormRow
          label="Accepts"
          element={<FormTagInput value={field.accepts} />}
          description="Which types of component are accepted as a value?" />

        <FormRow
          label="Is collection?"
          element={<FormToggle value={field.collection} />} />

        <FormRow
          label="Is required?"
          element={<FormToggle value={field.required} />} />

        <FormRow
          label="Is visible?"
          element={<FormToggle value={field.visible} />} />

        <FormRow
          label="Default"
          element={<FormTextInput value={field.default} />}
          description="Enter a default value to use when the value is empty." />

      </Form>
  </div>)
}
